apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-reisekostnad-api
  namespace: bidrag
  labels:
    team: bidrag
spec:
  image: {{ image }}
  leaderElection: true
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: reisekostnad-preprod
            envVarPrefix: DB
  liveness:
    path: /internal/actuator/health
    initialDelay: 60
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 60
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "2"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses:
    - https://bidrag-reisekostnad-api.dev.intern.nav.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod, i-sky
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    - name: BIDRAG_PERSON_SCOPE
      value: dev-fss.bidrag.bidrag-person
    - name: BIDRAG_PERSON_URL
      value: https://bidrag-person.dev-fss-pub.nais.io
    - name: POSTGRES_INSTANSEURL
      value: bidrag-dev-45a9:europe-north1:bidrag-reisekostnad-api
    - name: KJOEREPLAN_ARKIVERING
      value: "0 0/30 * * * ?"
    - name: DB_HOST
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_HOST}
    - name: DB_PORT
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_PORT}
    - name: DB_DATABASE
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_DATABASE}
    - name: DB_USERNAME
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_USERNAME}
    - name: DB_PASSWORD
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_PASSWORD}
    - name: DB_URL
      value: ${NAIS_DATABASE_BIDRAG_REISEKOSTNAD_API_REISEKOSTNAD_PREPROD_URL}
  accessPolicy:
    inbound:
      rules:
        - application: debug-dings
          namespace: plattformsikkerhet
          cluster: dev-gcp
        - application: bidrag-reisekostnad-ui
          namespace: bidrag
          cluster: dev-gcp
