name: bidrag-reisekostnad-api
ingresses: 
  - https://bidrag-reisekostnad-api.intern.nav.no
database:
  navn: reisekostnad-prod
  tier: db-g1-small
  auditlog: "on"
kafka:
  pool: nav-prod
replicas:
  min: 2
  max: 2
limits:
  memory: 2Gi
  cpu: "1"
requests:
  memory: 1Gi
  cpu: 200m
env:
  SPRING_PROFILES_ACTIVE: prod, i-sky
  BIDRAG_DOKUMENT_SCOPE: prod-fss.bidrag.bidrag-dokument
  BIDRAG_DOKUMENT_URL: https://bidrag-dokument.prod-fss-pub.nais.io
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io
  BIDRAG_REISEKOSTNAD_UI_URL: https://bidrag-reisekostnad.nav.no
  POSTGRES_INSTANSEURL: bidrag-prod-8f72:europe-north1:bidrag-reisekostnad-api
  KJOEREPLAN_ARKIVERING: "0 0 6 * * ?"
  KJOEREPLAN_DEAKTIVERING: "0 * 7 * * ?"
  KJOEREPLAN_FYLT_15: "0 30 6 * * ?"
  KJOEREPLAN_ANONYMISERING: "0 30 5 * * ?"
azure:
    inbound:
        rules:
        - application: bidrag-reisekostnad-ui
          namespace: bidrag
          cluster: prod-gcp
