spring:
  config.activate.on-profile: i-sky
  cloud.gcp.sql.database-name: ${DB_NAVN}
  cloud.gcp.sql.instance-connection-name: ${DB_URL}
  flyway:
    enabled: false
    locations: classpath:/db/migration
  jpa:
    hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  datasource:
    username: ${DB_BRUKERNAVN}
    password: ${DB_PASSORD}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAVN}?user=${DB_BRUKERNAVN}&password=${DB_PASSORD}
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1

---

springdoc:
  packages-to-scan: { no.nav.bidrag.reisekostnad.api}
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

integrasjon.bidrag.person.url: ${BIDRAG_PERSON_URL}

AZURE_BASE: https://login.microsoftonline.com/

no.nav.security.jwt:
  common:
    token-endpoint-url: ${AZURE_BASE}/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
  client.registration:
    bidrag-person:
      token-endpoint-url: ${no.nav.security.jwt.common.token-endpoint-url}
      grant-type: client_credentials
      scope: api://${BIDRAG_PERSON_SCOPE}/.default
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
  issuer.aad:
    discovery_url: ${AZURE_BASE}/${AZURE_APP_TENANT_ID}/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
  tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}
