-- Table: forelder

-- DROP TABLE forelder;

CREATE TABLE forelder
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    personident character varying(11) COLLATE pg_catalog."default",
    CONSTRAINT forelder_pkey PRIMARY KEY (id),
    CONSTRAINT uk_forelder_foedselsnummer UNIQUE (personident)
)

 TABLESPACE pg_default;