-- Table: barn

-- DROP TABLE barn;

CREATE TABLE barn
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    personident character varying(11) COLLATE pg_catalog."default",
    forespørsel_id integer,
    CONSTRAINT barn_pkey PRIMARY KEY (id),
    CONSTRAINT uk_barn_personident UNIQUE (personident),
    CONSTRAINT fk_forespørsel_id FOREIGN KEY (forespørsel_id)
        REFERENCES forespørsel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;
