-- Table: forespørsel

-- DROP TABLE forespørsel;

CREATE TABLE forespørsel
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    hovedpart_id integer,
    motpart_id integer,
    krever_samtykke boolean,
    opprettet timestamp without time zone,
    samtykket timestamp without time zone,
    journalført timestamp without time zone,
    deaktivert timestamp without time zone,
    CONSTRAINT forespørsel_pkey PRIMARY KEY (id),
    CONSTRAINT fk_hovedpart_id FOREIGN KEY (hovedpart_id)
        REFERENCES forelder (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_motpart_id FOREIGN KEY (motpart_id)
        REFERENCES forelder (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;